name: ci

on:
  push:
    branches: [ci]
  pull_request:
    branches: [ci]

jobs:

  ci:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Verify dependencies
      run: find -name go.mod -execdir go mod verify \;

    # - name: Build
    #   run: go build -v ./...

    # - name: Run go vet
    #   run: go vet ./...

    # - name: Install staticcheck
    #   run: go install honnef.co/go/tools/cmd/staticcheck@latest

    # - name: Run staticcheck
    #   run: staticcheck ./...

    # - name: Install golint
    #   run: go install golang.org/x/lint/golint@latest

    # - name: Run golint
    #   run: golint ./...

    # - name: Run tests
    #   run: go test -race -vet=off ./...